
services:
  mysql:
    image: 'mysql:latest'
    container_name: 'system-design'
    environment:
      - 'MYSQL_DATABASE=my_system'
      - 'MYSQL_PASSWORD=111111'
      - 'MYSQL_ROOT_PASSWORD=000000'
      - 'MYSQL_USER=chen_yi'
    ports:
      - '3306:3306'